version: '3.3'
services:
    webserver:
      build:
        context: .
      dns:
        - 8.8.8.8
        - 8.8.4.4
      #volumes:
      #  - ~/sources/mmi:/var/www/html
      restart: on-failure
      env_file: .env
      environment:
          UID: ${UID}
          GID: ${GID}
      tty: true
      stdin_open: true
